title: "Data analysis methods for ab initio molecular dynamics simulations"
name: "Lei Lei"
email: Lei.Lei@nottingham.ac.uk

url: "https://lei-lei-alpha.github.io/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/Molecular-Dynamics-Molecular-Cages" # the subpath of your site, e.g. "/blog"
repository: "Lei-Lei-alpha/Molecular-Dynamics-Molecular-Cages" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

header_feature_image: "./cage1.png"
header_feature_image_responsive: true

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax

# katex: true

plugins:
  - jekyll-feed

theme: jekyll-theme-cayman
