title: Molecular-Dynamics-Molecular-Cages
email: Lei.Lei@nottingham.ac.uk
name: "Lei Lei"
description: >- # this means to ignore newlines until "baseurl:"
  AIMD data analysis methods and part of the raw data for the paper "Supramolecular Proton Conductors Self-Assembled by Organic Cages"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lei-lei-alpha.github.io/Molecular-Dynamics-Molecular-Cages" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: leilei78814998
github_username:  Lei-Lei-alpha

# Build settings
markdown: kramdown
# remote_theme: pages-themes/cayman@v0.2.0
theme: Cayman
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


theme: jekyll-theme-cayman
