title: Molecular-Dynamics-Molecular-Cages
email: Lei.Lei@nottingham.ac.uk
name: "Lei Lei"
description: >- # this means to ignore newlines until "baseurl:"
  AIMD data analysis methods and part of the raw data for the paper "Supramolecular Proton Conductors Self-Assembled by Organic Cages"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lei-lei-alpha.github.io/Molecular-Dynamics-Molecular-Cages" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: leilei78814998
github_username:  Lei-Lei-alpha

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
source: "https://github.com/Lei-Lei-alpha/Molecular-Dynamics-Molecular-Cages/edit/master/docs"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-include-cache
# theme: jekyll-theme-cayman
# remote_theme: jekyll/minima

theme: jekyll-theme-cayman
